#!/bin/sh

case "$1" in
    start)
        printf "Starting Qt Calculator: "
        export QT_QPA_PLATFORM=eglfs
        export QT_QPA_EGLFS_INTEGRATION=eglfs_kms
        export QT_QPA_EGLFS_KMS_ATOMIC=1
        export QT_QPA_EGLFS_KMS_CONFIG=/etc/qt_kms.conf
        export XDG_RUNTIME_DIR=/tmp/runtime-root
        mkdir -p /tmp/runtime-root
        start-stop-daemon -S -b -m -p /var/run/qtcalc.pid $
            --exec /usr/bin/itisimplecal
        echo "OK"
        ;;
    stop)
        printf "Stopping Qt Calculator: "
        start-stop-daemon -K -p /var/run/qtcalc.pid
        echo "OK"
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
